constants:
  TARGET_PATH: $$CONFIG_PATH$$/$$$TARGET_NAME$$$
  LIBRARY_PATH: $$CONFIG_PATH$$/../
  WORK_DIR: $$$WORK_DIR$$$/work/$$$TARGET_NAME$$$
  PERSIST_DIR: $$$WORK_DIR$$$/persist/$$$TARGET_NAME$$$
---

general:
  logger:
    log-level: error
    file: $$WORK_DIR$$/log.txt
  monitor:
    enable: true
    sample-rate: 50
   
testcase:
  module: load
  module-options:
    input-directory: $$$TESTCASE_DIRECTORY$$$

trace:
  module: pin
  module-options:
    output-directory: $$WORK_DIR$$/traces
    pin-tool-path: $$$PINTOOL$$$
    pin-path: $$$PIN_PATH$$$/pin
    wrapper-path: $$TARGET_PATH$$
    rdrand: 0xabcdef0123456789
    environment:
      LD_LIBRARY_PATH: $$LIBRARY_PATH$$
      TEST_MODE: MICROWALK
    images:
      - $$$TARGET_NAME$$$
  options:
    input-buffer-size: 4
    
preprocess:
  module: pin
  module-options:
    output-directory: $$WORK_DIR$$/traces
    store-traces: true
    keep-raw-traces: false
  options:
    input-buffer-size: 2
    max-parallel-threads: 4
  
analysis:
  modules:
    - module: control-flow-leakage
      module-options:
        output-directory: $$PERSIST_DIR$$/results
        map-files:
          - $$TARGET_PATH$$.map
        dump-call-tree: false
        include-testcases-in-call-stacks: false
        
  options:
    input-buffer-size: 1
    max-parallel-threads: 1
